#ifndef WEIGHTED_F_FREE_EDGE_EDITING_SUBGRAPHS_H
#define WEIGHTED_F_FREE_EDGE_EDITING_SUBGRAPHS_H

#include "SubgraphC4P4.h"
#include "SubgraphP3.h"

#endif // WEIGHTED_F_FREE_EDGE_EDITING_SUBGRAPHS_H
