//
// Created by jonas on 27.02.20.
//

#ifndef WEIGHTED_F_FREE_EDGE_EDITING_PRUNEDDELTASEARCHSTRATEGY_H
#define WEIGHTED_F_FREE_EDGE_EDITING_PRUNEDDELTASEARCHSTRATEGY_H


class PrunedDeltaSearchStrategy : public SearchStrategyI {

};


#endif //WEIGHTED_F_FREE_EDGE_EDITING_PRUNEDDELTASEARCHSTRATEGY_H
