//
// Created by jonas on 27.02.20.
//

#ifndef WEIGHTED_F_FREE_EDGE_EDITING_SEARCH_STRATEGY_UTILS_H
#define WEIGHTED_F_FREE_EDGE_EDITING_SEARCH_STRATEGY_UTILS_H

#endif //WEIGHTED_F_FREE_EDGE_EDITING_SEARCH_STRATEGY_UTILS_H
